# Generated by Django 3.1.3 on 2023-11-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('Writer', models.TextField()),
                ('Number_of_volumes', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
