# Generated by Django 3.1.3 on 2023-11-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_auto_20231111_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Number_of_pages',
            field=models.PositiveIntegerField(),
        ),
    ]
