# Generated by Django 3.1.3 on 2023-11-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20231111_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Number_of_pages',
            new_name='number_of_pages',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Writer',
            new_name='writer',
        ),
    ]
